<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Naira Direct</title>
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/greenmouse-tech/image/upload/v1702897719/NairaDirect-Images/iyggly6czgiesicqthmh.png">
    <link rel="stylesheet" href="../frontend/assets/css/bootstrap.css">
    <link rel="stylesheet" href="../frontend/assets/css/style.css">
    <link rel="stylesheet" href="../frontend/assets/js/bootstrap.js">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<?php include('../frontend/include/layout/header.php'); ?>

<body onload="LoadTheme()">
    <div>
        <!-- hero sections -->
        <div class="referral-hero">
            <div class="container h-100">
                <div class="banner-control">
                    <h1>Terms and Conditions.</h1>
                </div>
            </div>
        </div>
        <!-- page content -->
        <div class="section-padding">
            <div class="container">
                <div class="row">
                    <div>
                        <p>This is a contract between you and NairaDirect, (hereinafter referred to as Naira Direct). By signing up to use an account through our website, you agree that you have read, understood, and accepted all of the terms and conditions contained in this Agreement, as well as our Privacy Policy.</p>
                        <p>This Agreement is legally binding and serves to govern your use of this site. Please read its terms carefully before registering your account because they affect your legal rights and obligations. If you do not agree with any of the terms contained herein, kindly refrain from using this service.</p>
                        <p>Naira Direct reserves the right to update, revise, modify, or otherwise, reissue these terms without prior notice.</p>
                    </div>
                    <div>
                        <h5 class="fw-bold">PART 1: GENERAL USE</h5>
                        <h6 class="mt-4 fw-bold">1. Basic Naira Direct Services.</h6>
                        <p><span class="fw-bold">1.1. Eligibility.</span> Our website and services are not directed to children under 18. We do not knowingly collect information from children under 18. If as a parent or guardian, you become aware that your child or ward child has provided us with any information without your consent, please contact us through details on this Privacy Policy.</p>
                        <p>Your eligibility to access certain Naira Direct services also depends on the country in which you reside. At the moment, Naira Direct operates in Nigeria, and is only available to users who hold Nigerian bank accounts.</p>
                        <p><span class="fw-bold">1.2. Naira Direct Services.</span> Your Naira Direct account ("Naira Direct Account") encompasses the following basic Naira Direct services:</p>
                        <ul>
                            <li>One or more hosted Digital Currency wallets that allow users store certain supported digital currencies – in this case, Bitcoin ("Digital Currency"), and track, transfer, and manage their supported Digital Currencies (the "Hosted Digital Currency Wallet")</li>
                            <li>An online wallet for both Fiat Currency (e.g Naira) and Digital Currency for use in connection with other Naira Direct Services.</li>
                        </ul>
                        <p class="fw-medium mt-4">The risk of loss in trading or holding Digital Currency can be substantial. You should therefore carefully consider whether trading or holding Digital Currency is suitable for you in light of your financial condition.</p>
                    </div>
                    <div>
                        <h5 class="fw-bold mt-3">2. Creating a Naira Direct Account.</h5>
                        <p><span class="fw-bold">2.1. Registration of Naira Direct Account.</span> In order to use any Naira Direct services, you must first register by providing your full name, e-mail address, password, and affirm your acceptance of this Agreement. Naira Direct may, at our sole discretion, revoke account registrations, and/or limit the number of Naira Direct Accounts a single user may establish and maintain at any time.</p>
                        <p><span class="fw-bold">2.2. Identity Verification.</span> In order to use certain features of the Naira Direct Services, like buying a Digital Currency, you may be required to provide Naira Direct with personal information, including, but not limited to, your name, address, telephone number, e-mail address, date of birth, Bank Verification Number (BVN), National Identification Number (NIN), and information regarding your bank account (e.g., financial institution and account number). By submitting these or any other personal information as may be required, you confirm that the information provided is accurate and authentic, and you agree to update Naira Direct if any information changes.</p>
                        <p class="fw-medium mt-4">You hereby authorise Naira Direct to, directly or through third parties, make any inquiries we consider necessary to verify your identity and/or protect against fraud, including to query identity information contained in public reports (e.g., your name, address, past addresses, or date of birth), to query account information associated with your linked bank account (e.g., name or account balance), and to take action we reasonably deem necessary based on the results of such inquiries and reports. You further authorise any and all third parties to which such inquiries or requests may be directed to fully respond to such inquiries or requests.</p>
                    </div>
                    <div>
                        <h5 class="fw-bold mt-3">3. Hosted Digital Currency Wallet.</h5>
                        <p><span class="fw-bold">3.1. In General.</span>  The Hosted Digital Currency Wallet services allow you send supported Digital Currency to, and request, receive, and store supported Digital Currency from, third parties pursuant to instructions you provide through the Naira Direct Site (each such transaction is a "Digital Currency Transaction").</p>
                        <p class="fw-medium mt-4">Naira Direct reserves the right to refuse to process or to cancel any pending Digital Currency Transaction as required by law or in response to a subpoena, court order, or other binding government order or to enforce transaction limits. Naira Direct cannot reverse a Digital Currency Transaction which has been broadcast to a Digital Currency network. The Hosted Digital Currency Wallet services are available only in connection with those Digital Currencies that Naira Direct, in its sole discretion, decides to support. Under no circumstances should you attempt to use your Hosted Digital Currency Wallet services to store, send, request, or receive digital currencies in any form that is not supported by Naira Direct. Naira Direct assumes no responsibility or liability in connection with any attempt to use Naira Direct Services for digital currencies that Naira Direct does not support.</p>
                        <p><span class="fw-bold">3.2. Digital Currency Transactions.</span>  Naira Direct processes supported Digital Currency according to the instructions received from its users and we do not guarantee the identity of any user, receiver, requester or other party. You should verify all transaction information prior to submitting instructions to Naira Direct. In the event you initiate a Digital Currency Transaction by entering the recipient's Digital Currency address on the network, a network fee will be incurred. Once submitted to a Digital Currency network, a Digital Currency Transaction will be unconfirmed for a period of time pending sufficient confirmation of the transaction by the Digital Currency network. A transaction is not complete while it is in a pending state. Funds associated with transactions that are in a pending state will be designated accordingly, and will not be included in your Naira Direct Account’s available balance or be available to conduct transactions. Naira Direct may charge network fees (miner fees) to process a Digital Currency transaction on your behalf. Naira Direct will calculate the network fee in its discretion, although Naira Direct will always notify you of the network fee at or before the time you authorise the transaction.</p>  
                        <p><span class="fw-bold">3.3. Digital Currency Storage & Transmission Delays.</span> Naira Direct securely stores all Digital Currency private keys in our control in a combination of online and offline storage. As a result, it may be necessary for Naira Direct to retrieve certain information from offline storage in order to facilitate a Digital Currency Transaction in accordance with your instructions, which may delay the initiation or crediting of such Digital Currency Transaction for 48 hours or more. You acknowledge and agree that a Digital Currency Transaction facilitated by Naira Direct may be delayed.</p>  
                        <p><span class="fw-bold">3.5 Advanced Protocols.</span> Unless specifically announced on our website or through some other official public statement of Naira Direct, we do not support metacoins, coloured coins, side chains, or other derivative, enhanced, or forked protocols, tokens, or coins which supplement or interact with a Digital Currency supported by Naira Direct (collectively, “Advanced Protocols”). Do not use your Naira Direct account to attempt to receive, request, send, store, or engage in any other type of transaction involving an Advanced Protocol. The Naira Direct platform is not configured to detect and/or secure Advanced Protocol transactions and Naira Direct assumes absolutely no responsibility whatsoever in respect to Advanced Protocols.</p>  
                        <p><span class="fw-bold">3.6 Operation of Digital Currency Protocols.</span> Naira Direct does not own or control the underlying software protocols which govern the operation of Digital Currencies supported on our platform. In general, the underlying protocols are open source and anyone can use, copy, modify, and distribute them. By using the Naira Direct platform, you acknowledge and agree that</p>
                        <ul>
                            <li>Naira Direct is not responsible for operation of the underlying protocols and that Naira Direct makes no guarantee of their functionality, security, or availability</li>
                            <li>The underlying protocols are subject to sudden changes in operating rules (a.k.a “forks”), and that such forks may materially affect the value, function, and/or even the name of the Digital Currency you store on the Naira Direct platform. In the event of a fork, you agree that Naira Direct may temporarily suspend Naira Direct operations (with or without advance notice to you) and that Naira Direct may, in its sole discretion, decide whether or not to support (or cease supporting) either branch of the forked protocol entirely. You acknowledge and agree that Naira Direct assumes absolutely no responsibility whatsoever in respect of an unsupported branch of a forked protocol.</li>
                        </ul>
                    </div>
                    <div>
                        <h5 class="fw-bold mt-3">4. General Use, Prohibited Use, and Termination.</h5>
                        <p><span class="fw-bold">4.1. Limited License.</span> We grant you a limited, nonexclusive, nontransferable license, subject to the terms of this Agreement, to access and use the Naira Direct Site, and related content, materials, information (collectively, the "Content") solely for approved purposes as permitted by Naira Direct from time to time. Any other use of the Naira Direct Site or Content is expressly prohibited and all other right, title, and interest in the Naira Direct Site or Content is exclusively the property of Naira Direct and its licensors. You agree you will not copy, transmit, distribute, sell, license, reverse engineer, modify, publish, or participate in the transfer or sale of, create derivative works from, or in any other way exploit any of the Content, in whole or in part. "bitkoin.africa", and "Naira Direct" and all logos related to Naira Direct Services or displayed on the Naira Direct Site are either trademarks or registered marks of Naira Direct or its licensors. You may not copy, imitate or use them without Naira Direct's prior written consent.</p>
                        <p><span class="fw-bold">4.2. Website Accuracy.</span> Although we intend to provide accurate and timely information on the Naira Direct Site, the Naira Direct Site (including, without limitation, the Content) may not always be entirely accurate, complete or current and may also include technical inaccuracies or typographical errors. In an effort to continue to provide you with as complete and accurate information as possible, information may be changed or updated from time to time without notice, including without limitation information regarding our policies, products and services. Accordingly, you should verify all information before relying on it, and all decisions based on information contained on the Naira Direct Site are your sole responsibility and we shall have no liability for such decisions. Links to third-party materials (including without limitation websites) may be provided as a convenience but are not controlled by us. You acknowledge and agree that we are not responsible for any aspect of the information, content, or services contained in any third-party materials or on any third party sites accessible or linked to the Naira Direct Site,</p>
                        <p><span class="fw-bold">4.3. Third-Party Applications.</span> If, to the extent permitted by Naira Direct from time to time, you grant express permission to a third party to access or connect to your Naira Direct Account, either through the third party's product or service or through the Naira Direct Site, you acknowledge that granting permission to a third party to take specific actions on your behalf does not relieve you of any of your responsibilities under this Agreement. You are fully responsible for all acts or omissions of any third party with access to your Naira Direct Account. Further, you acknowledge and agree that you will not hold Naira Direct responsible for, and will indemnify Naira Direct from, any liability arising out of or related to any act or omission of any third party with access to your Naira Direct Account.</p>
                        <p><span class="fw-bold">4.4. Prohibited Use.</span> In connection with your use of the Naira Direct Services, and your interactions with other users, and third parties you agree and represent you will not engage in any Prohibited Business or Prohibited Use defined herein. We reserve the right at all times to monitor, review, retain and/or disclose any information as necessary to satisfy any applicable law, regulation, sanctions programs, legal process or governmental request. We reserve the right to cancel and/or suspend your Naira Direct Account and/or block transactions or freeze funds immediately and without notice if we determine, in our sole discretion, that your Account is associated with a Prohibited Use and/or a Prohibited Business.</p>
                        <p><span class="fw-bold">4.5. Export Controls & Sanctions.</span> Your use of the Naira Direct Services and the Naira Direct Site is subject to international export controls and economic sanctions requirements. By sending, receiving, buying, selling, trading or storing Digital Currency through the Naira Direct Site or Naira Direct Services, you represent and warrant that you will conform with those requirements.</p>
                        <p><span class="fw-bold">4.6. Transactions Limits.</span> The use of all Naira Direct Services is subject to a limit on the amount of volume, stated in Fiat Currency terms, you may transact or transfer in a given period (e.g., daily). Your transaction limits may vary depending on your payment method, financial institution and other factors. To find out your limits, please contact your financial institution.</p>
                        <p><span class="fw-bold">4.7. Suspension, Termination, and Cancellation.</span> Naira Direct may: (a) suspend, restrict, or terminate your access to any or all of the Naira Direct Services, and/or (b) deactivate or cancel your Naira Direct Account if:</p>
                        <p class="fw-medium mt-4">You hereby authorise Naira Direct to, directly or through third parties, make any inquiries we consider necessary to verify your identity and/or protect against fraud, including to query identity information contained in public reports (e.g., your name, address, past addresses, or date of birth), to query account information associated with your linked bank account (e.g., name or account balance), and to take action we reasonably deem necessary based on the results of such inquiries and reports. You further authorise any and all third parties to which such inquiries or requests may be directed to fully respond to such inquiries or requests.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<?php include('../frontend/include/layout/footer.php'); ?>

</html>